@Host = http://localhost:8080


######### BY OFFSET #########


GET {{Host}}/ef/by-offset?page=3&pageSize=5

### SORTED

GET {{Host}}/ef/by-offset/sorted?page=1&pageSize=5&sort=-Quantity


######### BY CURSOR #########


GET {{Host}}/ef/by-cursor?pageSize=10&cursor=3

### SORTED

GET {{Host}}/ef/by-cursor/sorted?pageSize=10&sort=-Id

###

GET {{Host}}/ef/by-cursor/sorted?pageSize=10&sort=-Id&cursor=30|30

###

GET {{Host}}/ef/by-cursor/sorted?pageSize=30&sort=-Quantity

###

GET {{Host}}/ef/by-cursor/sorted?pageSize=30&sort=-Quantity&cursor=50|25
